name: Deploy WordPress to GoDaddy via rsync

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to GoDaddy WordPress Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Synchronize Files with GoDaddy WordPress Hosting Server
        uses: godaddy-wordpress/gd-wordpress-deployer@v1
        with:
          remote_host: '1263004.us28.ssh.myftpupload.com'
          ssh_user: 'git_deployer_d93c635f6a_1263004'
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          source_path: 'wp-content'
          deployment_dest: 'wp-content'
          cleanup_deleted_files: 'no'
